### ISSUE TITLE
Purge binaries and rely on gradle and maven instead

### ISSUE THREAD

**Issue by tobyweston** [xp-dojo/atdd-bank-account#5]
As discussed in #3 lets remove the binaries and .idea project files and rely on gradle instead.

I still think this isn't the approach going forward - I'd prefer a zero deps thing that "just works".

I also think that maven is lower touch than gradle (built in plugin) so propose we keep both the `pom.xml` and `gradle.build` files in sync. Open to discussed this though (if we do, we really should setup travis or circeci to keep us honest).

Once the whole thing is developed and we prepare for delivery, I think we should remove the build files as previously discussed.

**Comment by lithgow** [comment]
I know what you mean, I'd like zero deps too. Having said that, gradle actually comes closer to one touch build after checkout, in that you can use gradle wrapper at the terminal alongside (or within) you preferred IDE or text editor/VI/emacs ;)

IntelliJ should also prompt you to install the gradle plugin if you don't have it... I'm actually surprised it's not one of the defaults by now (it's been a while since I did a fresh install).

The issue with maven is that (outside of IDEs which may bundle it) you have to install something, so it's much less of a "batteries included" approach in that sense. It's also much more painful to extend.

+1 for travis or circle whatever we do!

**Comment by lithgow** [comment]
Now removed in the #6 branch, as I'd forgotten we had a separate issue for this!
